# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Design Portfolio
email: ngmanh1507@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specialising in Jekyll,
  HTML, CSS and JavaScript.
baseurl: "/designer-portfolio" # the subpath of your site, e.g. /blog
url: "http://nguyenmanh1507.github.io/designer-portfolio/" # the base hostname & protocol for your site
twitter_username: nguyenmanh1507
github_username:  nguyenmanh1507
google_username:  nguyenmanh1507

permalink: /:categories/:title

links: 
  - title: about
    url: /about
  - title: work
    url: /work
  - title: articles
    url: /articles
  - title: hire me
    url: /hire-me

# Build settings
markdown: kramdown
